apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: v8mluwkgb-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: v8mluwkgb-python 
  name: v8mluwkgb-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: v8mluwkgb-python 
